# Fundamantal concepts of tensorflow

##Introduction to tensors

In [7]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [8]:
# Create tensors with tf.constant
scaler=tf.constant(5)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [9]:
# Check the number of dimensions
scaler.ndim

0

In [10]:
# Create vector
vector=tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [11]:
# Create the number of dimensions
vector.ndim

1

In [12]:
# Matrix 
matrix=tf.constant([[4,5],[7,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [7, 8]], dtype=int32)>

In [13]:
# Matrix dimensions
matrix.ndim

2

In [14]:
# Create anotther matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [16]:
from numpy import int32
# Lets create a tensor 
# Tensor is an n-dimensional array of any numbers(0 dimensional tensor is scalor , 1 dimensional is vector, 2 dimensional tensor is matrix)
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]],dtype=int32)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

##Create tensors with tf.variable

In [18]:
changableTensor=tf.Variable([10,7])
unchangableTensor=tf.constant([10,7])
changableTensor,unchangableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
# Changing tensors with .assign()
changableTensor[0].assign(7)
changableTensor[0]


<tf.Tensor: shape=(), dtype=int32, numpy=7>

## creating random tensors


In [20]:
# Create two randoms (but the same) tensors
random1=tf.random.Generator.from_seed(42) # set seed from reproducability
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))

# are they equal?

random1,random2 ,random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## shuffle the order of elements in tensor


In [21]:
# Shuffle tensors
notShuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(notShuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
notShuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [23]:
tf.random.shuffle(notShuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [24]:
tf.random.set_seed(40)
tf.random.shuffle(notShuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

## otherways to make tensors


In [25]:
tf.ones([10,7])
# Or 
tf.ones(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## change numpy arrays to tensors

*   main difference is tensors can run on gpu  




In [27]:
# Numpy into arrays

import numpy as np
numpyArr=np.arange(1,25,dtype=np.int32)
numpyArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
a=tf.constant(numpyArr)
a


<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [29]:
b=tf.constant(numpyArr,shape=(3,2,4)) # 3*2*4 must be total number of elements
b

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## getting information from tensors

*   Shape
*   Rank
*   Axis or dimensions
*   Size





In [30]:
rank4Tensor=tf.zeros(shape=[2,3,4,5])
rank4Tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank4Tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank4Tensor.shape, rank4Tensor.ndim, tf.size(rank4Tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
# Get various attributes of our tensor

print('datatype of every element', rank4Tensor.dtype)
print('number of dimensions (rank)', rank4Tensor.ndim)
print("shape of tensor",rank4Tensor.shape)
print("Elements along the 0 axis:", rank4Tensor.shape[0])
print("Elements along the last axis:", rank4Tensor.shape[-1])
print('total number of elements in our tensor',tf.size(rank4Tensor).numpy())

datatype of every element <dtype: 'float32'>
number of dimensions (rank) 4
shape of tensor (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
total number of elements in our tensor 120


## Indexing tensors

In [34]:
# Get first 2 elements of each dimensions
rank4Tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
# Get first element from each dimension from each index except for the final one
rank4Tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank4Tensor[:,:,:1,:1]

<tf.Tensor: shape=(2, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]],


       [[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [37]:
# Create rank 2 tensor (2 dimension)
rank2Tensor=tf.constant([[10,7],[33,44]])
rank2Tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [33, 44]], dtype=int32)>

In [38]:
# Get the last element of each row of our data rank2 tensor
rank2Tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 44], dtype=int32)>

In [39]:
# Add in extra dimension to our rank 2 tensor
rank3Tensor=rank2Tensor[...,tf.newaxis]
rank3Tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[33],
        [44]]], dtype=int32)>

In [40]:
tf.expand_dims(rank2Tensor,axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[33],
        [44]]], dtype=int32)>

## manipulating tensors

In [41]:
# Add values to tensor by using addition
tensor=tf.constant([[10,7],[3,4]])

In [42]:
# Multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [43]:
# Subtraction if you want
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [44]:
# We can use the tensor function to multiply
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [45]:
# We can use tensor addition
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

## Matrix multiplication
matrix multiplication is also referred as dot product 

In [46]:
# Matrix multiplication in tensor flow
tensor1=tf.constant([[10,7],[3,4]])
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
# Alternative matrix multiplication
tensor1@tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
x=tf.constant([[1,2],[3,4],[5,6]]) # 3*3
y=tf.constant([[1,2,3],[4,5,6]]) # 3*2
tf.matmul(x,y) # 3*2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [49]:
# For multiplication inner dimensions must match
x@tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [50]:
# Transponse of matrix
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [51]:
# Multiplying matrix wiith transpose of matrix 
tf.matmul(tf.transpose(x),x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

## The dot product
matrix multiplication and dot product are the same
tf.matmul()
tf.tensordot()


In [52]:
a = tf.constant([[1,2],[3,4],[5,6]]) # 2*3
b = tf.constant([[7,8],[9,10],[11,12]]) # 3*2

In [53]:
# Perform the dot product on x and y (requires x and y to be transposed)
tf.tensordot(tf.transpose(a),b,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [54]:
# Perform the matrix multiplication on x and y
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [55]:
print(b)
print(tf.transpose(b))
print(tf.reshape(b,shape=(2,3)))
# Normally we use transpose for tansor multiplication rather than transpose

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


## changing datatypes of tensors



In [56]:
# Create a new tensor with default data type (float 32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [57]:
c=tf.constant([7,10])
c.dtype

tf.int32

In [58]:
# Change from float32 to float16 (reduces precision)
d=tf.cast(c ,dtype=tf.float16)
d , d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

In [59]:
# Change from int32 to float32
e=tf.cast(c,dtype=tf.float32)
e,e.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

## aggregating tensors

In [60]:
# Get the absolute values
d=tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### let go through the following aggregations


*   Get the minimum
*   Get the maximum
*   Get the mean of a tensor
*   Get the sum of a tensor



In [62]:
# Create a random tensor with values between 0 and 100 of size 50
e=tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92, 86, 80, 82, 46, 41, 37, 57, 90, 14, 32, 84,  6, 53, 27, 31, 23,
       84, 77, 40, 73,  9, 53, 43, 99, 79, 13, 31, 26,  2, 24, 92, 32, 68,
       56, 59, 43, 83, 33, 37, 90, 94, 75, 14, 34,  7, 78, 89, 55,  1])>

In [63]:
tf.size(e),e.shape,e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [64]:
# Find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [65]:
# Find the max
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [66]:
# Find the mean
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [67]:
# Find the sum
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2574>

In [68]:
# Find the variance
tf.math.reduce_variance(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=846.5696>

In [69]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.09587>

##find the postional max and min


In [70]:
# create a new tensor for postional max and min
p=tf.random.uniform(shape=[50])
p

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.74675906, 0.24612856, 0.52820086, 0.8276756 , 0.6183318 ,
       0.0846777 , 0.13903832, 0.04563856, 0.6154578 , 0.44305432,
       0.7431537 , 0.9795221 , 0.54386437, 0.21016955, 0.24788725,
       0.35024524, 0.03533351, 0.65845823, 0.24004912, 0.1725409 ,
       0.22278512, 0.2606182 , 0.37575412, 0.9490981 , 0.3538996 ,
       0.4968046 , 0.18215156, 0.87830687, 0.08035612, 0.9584689 ,
       0.11927223, 0.48161948, 0.46814215, 0.26376808, 0.33337045,
       0.9157454 , 0.8242643 , 0.00191033, 0.2706449 , 0.75256467,
       0.07479346, 0.25697482, 0.10337758, 0.5379051 , 0.2707088 ,
       0.02460349, 0.06105328, 0.42337906, 0.30669105, 0.30637336],
      dtype=float32)>

In [71]:
# Find the positional maximum
tf.argmax(p) ,p[tf.argmax(p)]

(<tf.Tensor: shape=(), dtype=int64, numpy=11>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9795221>)

In [72]:
# Find the positional minimum
tf.argmin(p) , p[tf.argmin(p)]

(<tf.Tensor: shape=(), dtype=int64, numpy=37>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0019103289>)

In [73]:
# Check for equality
p[tf.argmax(p)]==tf.reduce_max(p)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## Squeezing the matrix

In [80]:
# Create a tensor to get started
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [81]:
gSqueezed=tf.squeeze(g)
gSqueezed, gSqueezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One hot encoding tensor

In [83]:
# create a list of indices
someList=[1,2,3,4] # red,green,blue,purple
tf.one_hot(someList,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [85]:
# specify custom value for one hot encoding
tf.one_hot(someList,depth=4,on_value="wow deep learning",off_value="hmm convolution")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hmm convolution', b'wow deep learning', b'hmm convolution',
        b'hmm convolution'],
       [b'hmm convolution', b'hmm convolution', b'wow deep learning',
        b'hmm convolution'],
       [b'hmm convolution', b'hmm convolution', b'hmm convolution',
        b'wow deep learning'],
       [b'hmm convolution', b'hmm convolution', b'hmm convolution',
        b'hmm convolution']], dtype=object)>

## squaring, log, square root

In [86]:
w=tf.range(1,10)
w

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [91]:
# square root
tf.sqrt(tf.cast(w,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [99]:
# log
tf.math.log(tf.cast(w,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy interaction

In [104]:
n=tf.constant(np.array([3.,7.,10.]))
n, type(n)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 tensorflow.python.framework.ops.EagerTensor)

In [105]:
# convert tensor to numpy
n=np.array(n)
n ,type(n)

(array([ 3.,  7., 10.]), numpy.ndarray)

In [106]:
# convert numpy to tensor
i=tf.constant([3.])
i.numpy()

array([3.], dtype=float32)

## Finding access to GPU

In [5]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
!nvidia-smi

Sat Apr 15 10:41:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------